<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__('Import - Custom') ?></h3></td>
        </tr>
    </table>
</div>
<div class="dashboard-container">
    <table cellspacing="25" width="100%">
        <tr>
            <td>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Group Prices') ?></h4></div>
                    <fieldset class="config"><?php echo $this->getChildHtml('group_price'); ?></fieldset>
                </div>
            </td>
        </tr>
    </table>
</div>